### ISSUE TITLE
unexpected keyword argument 'ignore_cleanup_errors'

### ISSUE THREAD

**Issue by bob-carpenter** [pymc-devs/nutpie#141]
I ran into this error when trying the Stan example on the landing page:

```python
>>> import nutpie
>>> code = """
... data {
...     real mu;
... }
... parameters {
...     real x;
... }
... model {
...     x ~ normal(mu, 1);
... }
... """
>>> compiled = nutpie.compile_stan_model(code=code)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/nutpie/compile_stan.py", line 142, in compile_stan_model
    basedir = tempfile.TemporaryDirectory(ignore_cleanup_errors=True)
TypeError: __init__() got an unexpected keyword argument 'ignore_cleanup_errors'
```

It looks like rust is installed:

```
nutpie$ which rustup
/Users/bcarpenter/.cargo/bin/rustup
```

which means I could install nutpie without it balking or griping more than usual.

```
~$ pip install 'nutpie[stan]'

DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting nutpie[stan]
  Using cached nutpie-0.10.0.tar.gz (171 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyarrow>=12.0.0 (from nutpie[stan])
  Downloading pyarrow-17.0.0-cp39-cp39-macosx_10_15_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.9/site-packages (from nutpie[stan]) (2.0.3)
Collecting xarray>=2023.6.0 (from nutpie[stan])
  Downloading xarray-2024.6.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: arviz>=0.15.0 in /usr/local/lib/python3.9/site-packages (from nutpie[stan]) (0.16.1)
Collecting fastprogress>=1.0.3 (from nutpie[stan])
  Downloading fastprogress-1.0.3-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: bridgestan>=2.1.2 in /usr/local/lib/python3.9/site-packages (from nutpie[stan]) (2.3.0)
Requirement already satisfied: setuptools>=60.0.0 in /usr/local/lib/python3.9/site-packages (from arviz>=0.15.0->nutpie[stan]) (66.1.1)
Requirement already satisfied: matplotlib>=3.2 in /usr/local/lib/python3.9/site-packages (from arviz>=0.15.0->nutpie[stan]) (3.7.1)
Requirement already satisfied: numpy<2.0,>=1.21.0 in /usr/local/lib/python3.9/site-packages (from arviz>=0.15.0->nutpie[stan]) (1.25.0)
Requirement already satisfied: scipy>=1.8.0 in /usr/local/lib/python3.9/site-packages (from arviz>=0.15.0->nutpie[stan]) (1.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.9/site-packages (from arviz>=0.15.0->nutpie[stan]) (21.3)
Requirement already satisfied: h5netcdf>=1.0.2 in /usr/local/lib/python3.9/site-packages (from arviz>=0.15.0->nutpie[stan]) (1.3.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.9/site-packages (from arviz>=0.15.0->nutpie[stan]) (4.2.0)
Requirement already satisfied: xarray-einstats>=0.3 in /usr/local/lib/python3.9/site-packages (from arviz>=0.15.0->nutpie[stan]) (0.5.1)
Requirement already satisfied: dllist in /usr/local/lib/python3.9/site-packages (from bridgestan>=2.1.2->nutpie[stan]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.9/site-packages (from pandas>=2.0->nutpie[stan]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/site-packages (from pandas>=2.0->nutpie[stan]) (2022.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.9/site-packages (from pandas>=2.0->nutpie[stan]) (2023.3)
Collecting packaging (from arviz>=0.15.0->nutpie[stan])
  Downloading packaging-24.1-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: h5py in /usr/local/lib/python3.9/site-packages (from h5netcdf>=1.0.2->arviz>=0.15.0->nutpie[stan]) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.2->arviz>=0.15.0->nutpie[stan]) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.2->arviz>=0.15.0->nutpie[stan]) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.2->arviz>=0.15.0->nutpie[stan]) (4.34.4)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.2->arviz>=0.15.0->nutpie[stan]) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.2->arviz>=0.15.0->nutpie[stan]) (9.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.2->arviz>=0.15.0->nutpie[stan]) (2.4.7)
Requirement already satisfied: importlib-resources>=3.2.0 in /usr/local/lib/python3.9/site-packages (from matplotlib>=3.2->arviz>=0.15.0->nutpie[stan]) (5.12.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=2.0->nutpie[stan]) (1.16.0)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.9/site-packages (from importlib-resources>=3.2.0->matplotlib>=3.2->arviz>=0.15.0->nutpie[stan]) (3.6.0)
Downloading fastprogress-1.0.3-py3-none-any.whl (12 kB)
Downloading pyarrow-17.0.0-cp39-cp39-macosx_10_15_x86_64.whl (29.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 29.0/29.0 MB 100.5 MB/s eta 0:00:00
Downloading xarray-2024.6.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 39.3 MB/s eta 0:00:00
Downloading packaging-24.1-py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.0/54.0 kB 1.9 MB/s eta 0:00:00
Building wheels for collected packages: nutpie
  Building wheel for nutpie (pyproject.toml) ... done
  Created wheel for nutpie: filename=nutpie-0.10.0-cp39-cp39-macosx_10_12_x86_64.whl size=627881 sha256=744e85aba52a9ac129e98500e075ac25dc3f85739b9a3f3391b6337e0f47dfb0
  Stored in directory: /Users/bcarpenter/Library/Caches/pip/wheels/f7/3d/02/0e50dd893a6298aaaa4f00130e176afd4d5a475ce6fb9cf974
Successfully built nutpie
Installing collected packages: pyarrow, packaging, fastprogress, xarray, nutpie
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Attempting uninstall: packaging
    Found existing installation: packaging 21.3
    Uninstalling packaging-21.3:
      Successfully uninstalled packaging-21.3
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  Attempting uninstall: xarray
    Found existing installation: xarray 2023.1.0
    Uninstalling xarray-2023.1.0:
      Successfully uninstalled xarray-2023.1.0
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed fastprogress-1.0.3 nutpie-0.10.0 packaging-24.1 pyarrow-17.0.0 xarray-2024.6.0
```

**Comment by maresb** [comment]
Thanks @bob-carpenter for the bug report!

Your Python version is quite old; 3.9 is almost a year outside of the [support lifecycle](https://scientific-python.org/specs/spec-0000/) for scientific Python. This bug has been fixed in more recent versions of nutpie that are not installable on 3.9.

Is it possible for you to upgrade to at least Python 3.10?

**Comment by bob-carpenter** [comment]
Installed everything again and am now getting a different error where nutpie can't find BridgeStan:

```
nutpie$ python3
Python 3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import nutpie
>>> import bridgestan
>>> code = """
... data {
...     real mu;
... }
... parameters {
...     real x;
... }
... model {
...     x ~ normal(mu, 1);
... }
... """
>>> compiled = nutpie.compile_stan_model(code=code)
BridgeStan not found at location specified by $BRIDGESTAN environment variable, downloading version 2.5.0 to /Users/bcarpenter/.bridgestan/bridgestan-2.5.0
Failed to download BridgeStan 2.5.0 from github.com.
Retrying ({i+1}/{RETRIES})...
Failed to download BridgeStan 2.5.0 from github.com.
Retrying ({i+1}/{RETRIES})...
```

I see `$BRIDGESTAN environment variable` but I don't see how to set that.  bridgestan is a Python package that's installed, as you can see by my ability to import it.  So I'm not sure what that environment variable should be.

**Comment by aseyboldt** [comment]
The bridgestan python module has the somewhat peculiar approach to download its own release tarball to get at the stan source (which is part of the bridgestan repo as a submodule), because the stan source is not distributed with the pip package itself. I don't really know why it is doing it that way.

I don't know why it would not be able to download the sources however, it does for me if I remove the .bridgestan directory.

Could this be some file system or network problem? Does it work if you call bridgestan directly, using something like
```
with open("model.stan", "w") as file:
    file.write(code)
bridgestan.compile_model("model.stan")
```

**Comment by bob-carpenter** [comment]
Updating Python broke ssh, so I just manually unpacked the bridgestan release tarball from GitHub into the correct location, `~/.bridgestan/bridgestan-2.5.0`.   After I did this, I was able to run nutpie according to the README.md instructions and get an arViz object out, which I can hopefully decode without more help. 

Thanks!

**Comment by aseyboldt** [comment]
> Updating Python broke ssh

That's a somewhat scary sentence ;-)
But glad to hear it work now. Don't hesitate to open more issues if run into additonal problems.

**Comment by bob-carpenter** [comment]
It only broke Python's connection to ssh and the Python installer warned me it did that.  I just didn't realize I'd need it for cmdstanpy.

I now have both systems fitting the same model and data and instrumented for timing.  In my simple tests, nutpie appears to be between 1.5 and 3 times faster than CmdStanPy when both are run multi-threaded, with similar error distributions.  There's a bigger speedup for simpler/smaller models, which makes sense as they spend more time on sampling code and less on gradient code.  I kicked off a longer eval and will share results on both the Stan and NumPy forums when I'm done.  Hopefully we'll be able to incorporate the improvements from nutpie into Stan soon to close this gap.  Thanks again for the help getting this running.

**Comment by aseyboldt** [comment]
That sounds great!
If you like, you can also give `nutpie.sample(compiled, low_rank_modified_mass_matrix=True)` a try, that should improve sampling performance for models with correlations. It's not tested all that much yet, and there seems to be a bug that occasionally leads to a panic that I haven't tracked down yet, but in by testing it helps (sometimes a lot) for ~20% of models in posteriordb.

**Comment by aseyboldt** [comment]
@bob-carpenter Not sure it's of any use to you, but just in case here is a small benchmarking tool I'm using to run and compare with posteriordb: https://github.com/aseyboldt/samplerlab
