### ISSUE TITLE
JAX backend fails for a simple `pymc`  linear regression model

### ISSUE THREAD

**Issue by trendelkampschroer** [pymc-devs/nutpie#157]
# Minimal example 

```python
import time

import arviz as az
import numpy as np
import nutpie
import pandas as pd
import pymc as pm

BETA = [1.0, -1.0, 2.0, -2.0]
SIGMA = 10.0


def generate_data(num_samples: int = 1000) -> pd.DataFrame:
    rng = np.random.default_rng(42)
    dims = len(BETA)
    X = rng.normal(size=(num_samples, dims))
    y = X.dot(BETA) + SIGMA * rng.normal(size=num_samples)
    frame = pd.DataFrame(data=X, columns=[f"x_{i+1}" for i in range(dims)])
    frame["y"] = y
    return frame


def make_model(frame: pd.DataFrame) -> pm.Model:
    predictors = [col for col in frame.columns if col.startswith("x")]
    observation_idx = [i for i in range(len(frame))]
    coords = {"observation_idx": observation_idx, "predictors": predictors}

    with pm.Model(coords=coords) as model:
        # Data
        x = pm.Data("x", frame[predictors], dims=["observation_idx", "predictor"])
        y = pm.Data("y", frame["y"], dims="observation_idx")

        # Population level
        beta = pm.Normal("beta", mu=0.0, sigma=1.0, dims="predictor")
        sigma = pm.HalfNormal("sigma", sigma=10.0)

        # Linear model
        mu = (beta * x).sum(axis=-1)

        # Likelihood
        pm.Normal("y_obs", mu=mu, sigma=sigma, observed=y, shape=mu.shape)

    return model


if __name__ == "__main__":
    frame = generate_data(num_samples=10_000)
    model = make_model(frame)

    kwargs = dict(backend="jax", gradient_backend="jax")
    t0 = time.time()
    trace = nutpie.sample(nutpie.compile_pymc_model(model, **kwargs))
    t = time.time() - t0
    print(f"Time for nutpie (compiled, {kwargs=}) sampling is {t=:.3f}s.")
    summary = az.summary(trace, var_names=["beta", "sigma"], round_to=4).loc[:, ["mean", "hdi_3%", "hdi_97%", "ess_bulk", "ess_tail", "r_hat"]]
    print(summary)

```

# Error message

```
thread 'nutpie-worker-3' panicked at /Users/runner/miniforge3/conda-bld/nutpie_1722020254444/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nuts-rs-0.12.1/src/sampler.rs:576:18:
Could not send sampling results to main thread.: SendError { .. }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File ".../linear_regression.py", line 52, in <module>
thread 'nutpie-worker-0' panicked at /Users/runner/miniforge3/conda-bld/nutpie_1722020254444/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nuts-rs-0.12.1/src/sampler.rs:576:18:
Could not send sampling results to main thread.: SendError { .. }
    trace = nutpie.sample(nutpie.compile_pymc_model(model, **kwargs))
            ^^thread 'nutpie-worker-6' panicked at /Users/runner/miniforge3/conda-bld/nutpie_1722020254444/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nuts-rs-0.12.1/src/sampler.rs:576:18:
Could not send sampling results to main thread.: SendError { .. }
^^thread 'nutpie-worker-1' panicked at /Users/runner/miniforge3/conda-bld/nutpie_1722020254444/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nuts-rs-0.12.1/src/sampler.rs:576:18:
Could not send sampling results to main thread.: SendError { .. }
^^^^^^^^^^thread 'nutpie-worker-2' panicked at /Users/runner/miniforge3/conda-bld/nutpie_1722020254444/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/nuts-rs-0.12.1/src/sampler.rs:576:18:
Could not send sampling results to main thread.: SendError { .. }
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.12/site-packages/nutpie/sample.py", line 636, in sample
    result = sampler.wait()
             ^^^^^^^^^^^^^^
  File ".../lib/python3.12/site-packages/nutpie/sample.py", line 388, in wait
    self._sampler.wait(timeout)
RuntimeError: All initialization points failed

Caused by:
    Logp function returned error: Python error: TypeError: _compile_pymc_model_jax.<locals>.make_logp_func.<locals>.logp() got multiple values for argument 'x'

```

Sampling with `backend="numba"` and `gradient_backend="pytensor"`  runs successfully.

**Comment by aseyboldt** [comment]
That you for the bug report. I had seen something possibly related recently, but didn't manage to find an example in a smaller model. This example should make it much easier to find the problem.

Right now you can work around the issue by freezing the pymc model:

```python
from pymc.model.transform.optimization import freeze_dims_and_data
trace = nutpie.sample(nutpie.compile_pymc_model(freeze_dims_and_data(model), **kwargs))
```

**Comment by aseyboldt** [comment]
Well, that was easier than I though, and won't be hard to fix. The problem is that the argument name for the point in parameter space is `x` and if any shared variable (like the data) is also called `x` this will give an argument name collision.

**Comment by trendelkampschroer** [comment]
@aseyboldt : Thanks a lot for the very helpful reply. I renamed 'x' -> 'X' and now things are working. 

This is really good to know, but probably something that should either be fixed by ensuring that a unique name for the point in parameter space is used, or forbidding `x` as name in the model (which would be a bit cumbersome, since predictors are often denoted by 'x').

On the upside using JAX gives a very nice speedup on my machine (Apple M1) :-).

**Comment by aseyboldt** [comment]
Yes, definitely needs a fix, I'll push one soon.

Out of curiosity (I don't have a apple), could you do me a small favor and run this with jax and numba and tell me what the compile and the runtime is each time?

### jax

```
frame = generate_data(num_samples=10_000)
model = make_model(frame)

kwargs = dict(backend="jax", gradient_backend="jax")

t0 = time.time()
compiled = nutpie.compile_pymc_model(model, **kwargs)
print(f"compile time: {time.time() - t0}")

t0 = time.time()
trace = nutpie.sample(compiled)
t = time.time() - t0
print(f"Time for nutpie (compiled, {kwargs=}) sampling is {t=:.3f}s.")
summary = az.summary(trace, var_names=["beta", "sigma"], round_to=4).loc[:, ["mean", "hdi_3%", "hdi_97%", "ess_bulk", "ess_tail", "r_hat"]]
print(summary)
```

### numba

```
frame = generate_data(num_samples=10_000)
model = make_model(frame)

kwargs = dict(backend="numba", gradient_backend="jax")

t0 = time.time()
compiled = nutpie.compile_pymc_model(model, **kwargs)
print(f"compile time: {time.time() - t0}")

t0 = time.time()
trace = nutpie.sample(compiled)
t = time.time() - t0
print(f"Time for nutpie (compiled, {kwargs=}) sampling is {t=:.3f}s.")
summary = az.summary(trace, var_names=["beta", "sigma"], round_to=4).loc[:, ["mean", "hdi_3%", "hdi_97%", "ess_bulk", "ess_tail", "r_hat"]]
print(summary)
```

**Comment by trendelkampschroer** [comment]
# jax

```
compile time for kwargs={'backend': 'jax', 'gradient_backend': 'jax'}: 1.016s
Time for nutpie (compiled, kwargs={'backend': 'jax', 'gradient_backend': 'jax'}) sampling is t=2.094s.
```

# numba

```compile time for kwargs={'backend': 'numba', 'gradient_backend': 'pytensor'}: 3.835s
Time for nutpie (compiled, kwargs={'backend': 'numba', 'gradient_backend': 'pytensor'}) sampling is t=0.564s.
```

**Comment by trendelkampschroer** [comment]
I hope that helps. I have another follow up question: While I observe a great speed-up when using the JAX backend on my M1 Apple machine, I observe significantly slower sampling with the JAX backend compared to Numba/Pytensor when running on a Google Cloud VM with a lot more cores (32) and memory. This is for a hierarchical linear regression with thousands of groups and a couple of predictors.

On the VM sampling with the "jax" backend is about 30% slower compared to the "numba" backend. Specifically I observe that for the "numba" backend I get a couple of  (4-8) thread/CPU bars in `htop` with 100%, while for the JAX backend all 32 bars show "some occupancy at leass than 50%".

If you have any ideas/insights what could cause this and also how to ensure best performance, then I'd be glad for any suggestions.

**Comment by aseyboldt** [comment]
Thanks for the numbers :-)

First, I think it is important to distinguish compile time and sampling time. The numbers you just gave me show that the numba backend samples faster on the mac as well, only the compile time is much larger. If the model get's bigger the compile time will play less of a role, because it doesn't depend much on the data size.

I think what you observe with the jax backend is an issue with how the jax backend currently works:
The chains run in different threads that are controlled in the rust code. With the numba backend the python interpreter is only used to generate the logp function, all sampling happens without any involvement of python. But doing this with jax is currently much harder (I hope this will change in the not too distant future though).
jax compiles the logp function, but I can't easily access this compiled function from rust. So instead I have to call a python function that then calls the compiled jax function. While a bit silly, that wouldn't be too bad if python didn't have the GIL. But the GIL ensures that only one thread (ie chain) can use the python interpreter at the same time. So each logp function evaluation does something like the following: 

- Acquire the gil (ie wait until no other thread is holding the GIL)
- start the jax logp function 
- release the gil
- do the actual logp fucniton evaluation (while not holding the gil)
- acquire the gil
- get access to the results
- release the gil

If the computation of the logp function takes a long time, and there aren't that many threads, then most of the time only one or even no thread will hold the gil, because each threads spends most of its time in the "do the actual logp function evaluation" phase, and all is good.
But if the logp function evaluation is relatively quick, then more than one thread will try to acquire the gil at the same time, and this means that the threads sit around waiting. Ie "low occupancy".

There are two things that might make this situation better in the future:
- python 3.13 has a new build without the gil. That isn't supported by jax and many other libraries at the time, but I hope this will change quickly.
- Jax might make it easier to call the compiled functions from other languages, so that I don't have to go through python to call the compiled function, which would avoid the whole problem to begin with.

In the meantime: If the cores of your machine aren't used well, you can at least try to limit the number of threads that run at the same time by setting the `cores` argument to sample to something smaller. This can reduce the lock contention and give you a modest speedup. It won't really fix the problem though...

If you are willing to go to some extra lengths: You can start multiple separate processes that sample your model (with different seeds!) and then combine the traces. This is much more annoying, but should completely avoid the lock contention. In that case you can run into other issues however, for instance if each process tries to use all available cores on the machine. Fixing that would then require using `threadpoolctl` and/or `tasksel` or some jax environment variable flags.

I hope that helps to clear it up a bit :-)

**Comment by trendelkampschroer** [comment]
Thanks @aseyboldt this is really helpful. Do you know of a minimal example for the "start multilple separate processes" approach. I have seen https://discourse.pymc.io/t/harnessing-multiple-cores-to-speed-up-fits-with-small-number-of-chains/7669 where the idea is to concatenate multiple smaller chains to more efficiently harness the CPUs on a machine. 
I'd e.g. try to use `joblib` for that but I am not sure how much that interferes with the PyMC and nutpie internals. If you have any pointers I'd be very glad to look into it.

**Comment by aseyboldt** [comment]
For sampling in separate processes:

```python
# At the very start...
import os
os.environ["JOBLIB_START_METHOD"] = "forkserver"

import joblib
from joblib import parallel_config, Parallel, delayed
import arviz

def run_chain(data, idx, seed):
    model = make_model(data)
    seeds = np.random.SeedSequence(seed)
    seed = np.random.default_rng(seeds.spawn(idx + 1)[-1]).integers(2 ** 63)
    compiled = nutpie.compile_pymc_model(model, backend="jax", gradient_backend="jax")
    trace = nutpie.sample(compiled, seed=seed, chains=1, progress_bar=False)
    return trace.assign_coords(chain=[idx])

with parallel_config(n_jobs=10, prefer='processes'):
   traces = Parallel()(delayed(run_chain)(frame, i, 123) for i in range(10))

trace = arviz.concat(traces, dim="chain")
```

This comes with quite a bit of overhead (mostly constant though), so probably not worth it for smaller models.


Funnily enough, I see big differences between 

```
# Option 1
mu = (beta * x).sum(axis=-1)

# Option 2
mu = x @ beta
```

And jax and numba react quite differently. Maybe an issue with the blas config? What blas implementation are you using?

(on conda-forge you can choose it as explained here: https://conda-forge.org/docs/maintainer/knowledge_base/#switching-blas-implementation)
I think on M1 accelerate is usually the fastest).

**Comment by trendelkampschroer** [comment]
Thanks a lot for the again very helpful suggestions. I will benchmark the two versions of the "dot-product" to see whether I observe different performance.

Regarding BLAS

On Apple-M1 I have
```
blas                      2.124                  openblas    conda-forge
blas-devel                3.9.0           24_osxarm64_openblas    conda-forge
libblas                   3.9.0           24_osxarm64_openblas    conda-forge
libcblas                  3.9.0           24_osxarm64_openblas    conda-forge
liblapack                 3.9.0           24_osxarm64_openblas    conda-forge
liblapacke                3.9.0           24_osxarm64_openblas    conda-forge
libopenblas               0.3.27          openmp_h517c56d_1    conda-forge
openblas                  0.3.27          openmp_h560b219_1    conda-forge
```
and on the VM
```
blas                      2.120                       mkl    conda-forge
blas-devel                3.9.0            20_linux64_mkl    conda-forge
libblas                   3.9.0            20_linux64_mkl    conda-forge
libcblas                  3.9.0            20_linux64_mkl    conda-forge
```
I can try to use the accelerate BLAS. But I am more curious to speed up things on the VM now.
