### ISSUE TITLE
Import fails with ValueError

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/nutpie#16]
Installing v0.3.0 with `maturin` results in a clean install, but importing nutpie fails:

```
>>> import nutpie
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cfonnesbeck/GitHub/nutpie/nutpie/__init__.py", line 4, in <module>
    from .compile_pymc import compile_pymc_model
  File "/Users/cfonnesbeck/GitHub/nutpie/nutpie/compile_pymc.py", line 13, in <module>
    from aeppl.logprob import CheckParameterValue
  File "/Users/cfonnesbeck/miniforge3/envs/pie/lib/python3.9/site-packages/aeppl/__init__.py", line 9, in <module>
    from aeppl.joint_logprob import factorized_joint_logprob, joint_logprob
  File "/Users/cfonnesbeck/miniforge3/envs/pie/lib/python3.9/site-packages/aeppl/joint_logprob.py", line 14, in <module>
    from aeppl.rewriting import construct_ir_fgraph
  File "/Users/cfonnesbeck/miniforge3/envs/pie/lib/python3.9/site-packages/aeppl/rewriting.py", line 138, in <module>
    def local_lift_DiracDelta(fgraph, node):
  File "/Users/cfonnesbeck/miniforge3/envs/pie/lib/python3.9/site-packages/aesara/tensor/rewriting/basic.py", line 149, in register_canonicalize
    compile.optdb["canonicalize"].register(
  File "/Users/cfonnesbeck/miniforge3/envs/pie/lib/python3.9/site-packages/aesara/graph/rewriting/db.py", line 339, in register
    super().register(name, rewriter, *tags, **kwargs)
  File "/Users/cfonnesbeck/miniforge3/envs/pie/lib/python3.9/site-packages/aesara/graph/rewriting/db.py", line 71, in register
    raise ValueError(f"The tag '{name}' is already present in the database.")
ValueError: The tag 'local_lift_DiracDelta' is already present in the database.
```

Running Aesara 2.8.7 and PyMC 4.4.0 on Python 3.9.0 on macOS 13.0.1

**Comment by fonnesbeck** [comment]
Can confirm import works now. I just get an llvm warning:

```
/Users/cfonnesbeck/miniforge3/envs/pie/lib/python3.9/site-packages/llvmlite/llvmpy/__init__.py:3: UserWarning: The module `llvmlite.llvmpy` is deprecated and will be removed in the future.
  warnings.warn(
/Users/cfonnesbeck/miniforge3/envs/pie/lib/python3.9/site-packages/llvmlite/llvmpy/core.py:8: UserWarning: The module `llvmlite.llvmpy.core` is deprecated and will be removed in the future. Equivalent functionality is provided by `llvmlite.ir`.
  warnings.warn(
```
